#!/bin/bash

rm -rf files report

tar -zxf files.tar.gz

../dupd
../dupd help
../dupd scan --path `pwd`/files -q
../dupd scan --path `pwd`/files -v
../dupd scan --path `pwd`/files -v -v
../dupd scan --path `pwd`/files -v -v -v
../dupd scan --path `pwd`/files -v -v -v -v

../dupd report --cut `pwd`/files/ | \
    grep -v "Duplicate report from database" | tee report

sort report > report.sorted

diff output1 report.sorted
RV=$?
if [ "$RV" != "0" ]; then
    T1="FAIL with default options"
else
    T1="OK with default options"
fi

../dupd scan --path `pwd`/files -v --intblocks 12

../dupd report --cut `pwd`/files/ | \
    grep -v "Duplicate report from database" | tee report

sort report > report.sorted

diff output1 report.sorted
RV=$?
if [ "$RV" != "0" ]; then
    T2="FAIL with intblocks"
else
    T2="OK with intblocks"
fi

echo
echo $T1
echo $T2
